//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery3SelfHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.Works = new HashSet<Work>();
        }
    
        public string Name { get; set; }
        public string Speciality { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<Work> Works { get; set; }
    }
}
