//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Gallery4Phone.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsArtist", Namespace="http://schemas.datacontract.org/2004/07/Gallery3SelfHost.DTO")]
    public partial class clsArtist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private string PhoneField;
        
        private string SpecialityField;
        
        private System.Collections.ObjectModel.ObservableCollection<Gallery4Phone.ServiceReference1.clsWork> WorksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Speciality {
            get {
                return this.SpecialityField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialityField, value) != true)) {
                    this.SpecialityField = value;
                    this.RaisePropertyChanged("Speciality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Gallery4Phone.ServiceReference1.clsWork> Works {
            get {
                return this.WorksField;
            }
            set {
                if ((object.ReferenceEquals(this.WorksField, value) != true)) {
                    this.WorksField = value;
                    this.RaisePropertyChanged("Works");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsWork", Namespace="http://schemas.datacontract.org/2004/07/Gallery3SelfHost.DTO")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gallery4Phone.ServiceReference1.clsPainting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gallery4Phone.ServiceReference1.clsPhotograph))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Gallery4Phone.ServiceReference1.clsSculpture))]
    public partial class clsWork : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ArtistNameField;
        
        private System.DateTime DateField;
        
        private string NameField;
        
        private decimal ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistName {
            get {
                return this.ArtistNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistNameField, value) != true)) {
                    this.ArtistNameField = value;
                    this.RaisePropertyChanged("ArtistName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsPainting", Namespace="http://schemas.datacontract.org/2004/07/Gallery3SelfHost.DTO")]
    public partial class clsPainting : Gallery4Phone.ServiceReference1.clsWork {
        
        private System.Nullable<float> HeightField;
        
        private string TypeField;
        
        private System.Nullable<float> WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsPhotograph", Namespace="http://schemas.datacontract.org/2004/07/Gallery3SelfHost.DTO")]
    public partial class clsPhotograph : Gallery4Phone.ServiceReference1.clsWork {
        
        private System.Nullable<float> HeightField;
        
        private string TypeField;
        
        private System.Nullable<float> WidthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsSculpture", Namespace="http://schemas.datacontract.org/2004/07/Gallery3SelfHost.DTO")]
    public partial class clsSculpture : Gallery4Phone.ServiceReference1.clsWork {
        
        private string MaterialField;
        
        private System.Nullable<float> WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Material {
            get {
                return this.MaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialField, value) != true)) {
                    this.MaterialField = value;
                    this.RaisePropertyChanged("Material");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetArtistNames", ReplyAction="http://tempuri.org/IService1/GetArtistNamesResponse")]
        System.IAsyncResult BeginGetArtistNames(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetArtistNames(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetArtist", ReplyAction="http://tempuri.org/IService1/GetArtistResponse")]
        System.IAsyncResult BeginGetArtist(string prArtistName, System.AsyncCallback callback, object asyncState);
        
        Gallery4Phone.ServiceReference1.clsArtist EndGetArtist(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UpdateArtist", ReplyAction="http://tempuri.org/IService1/UpdateArtistResponse")]
        System.IAsyncResult BeginUpdateArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState);
        
        int EndUpdateArtist(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertArtist", ReplyAction="http://tempuri.org/IService1/InsertArtistResponse")]
        System.IAsyncResult BeginInsertArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState);
        
        int EndInsertArtist(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteArtist", ReplyAction="http://tempuri.org/IService1/DeleteArtistResponse")]
        System.IAsyncResult BeginDeleteArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState);
        
        int EndDeleteArtist(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/UpdateWork", ReplyAction="http://tempuri.org/IService1/UpdateWorkResponse")]
        System.IAsyncResult BeginUpdateWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState);
        
        int EndUpdateWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/InsertWork", ReplyAction="http://tempuri.org/IService1/InsertWorkResponse")]
        System.IAsyncResult BeginInsertWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState);
        
        int EndInsertWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/DeleteWork", ReplyAction="http://tempuri.org/IService1/DeleteWorkResponse")]
        System.IAsyncResult BeginDeleteWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState);
        
        int EndDeleteWork(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Gallery4Phone.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetArtistNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetArtistNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetArtistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetArtistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Gallery4Phone.ServiceReference1.clsArtist Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Gallery4Phone.ServiceReference1.clsArtist)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateArtistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateArtistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertArtistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertArtistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteArtistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteArtistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateWorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateWorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertWorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertWorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteWorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteWorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Gallery4Phone.ServiceReference1.IService1>, Gallery4Phone.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetArtistNamesDelegate;
        
        private EndOperationDelegate onEndGetArtistNamesDelegate;
        
        private System.Threading.SendOrPostCallback onGetArtistNamesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetArtistDelegate;
        
        private EndOperationDelegate onEndGetArtistDelegate;
        
        private System.Threading.SendOrPostCallback onGetArtistCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateArtistDelegate;
        
        private EndOperationDelegate onEndUpdateArtistDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateArtistCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertArtistDelegate;
        
        private EndOperationDelegate onEndInsertArtistDelegate;
        
        private System.Threading.SendOrPostCallback onInsertArtistCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteArtistDelegate;
        
        private EndOperationDelegate onEndDeleteArtistDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteArtistCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateWorkDelegate;
        
        private EndOperationDelegate onEndUpdateWorkDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertWorkDelegate;
        
        private EndOperationDelegate onEndInsertWorkDelegate;
        
        private System.Threading.SendOrPostCallback onInsertWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteWorkDelegate;
        
        private EndOperationDelegate onEndDeleteWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetArtistNamesCompletedEventArgs> GetArtistNamesCompleted;
        
        public event System.EventHandler<GetArtistCompletedEventArgs> GetArtistCompleted;
        
        public event System.EventHandler<UpdateArtistCompletedEventArgs> UpdateArtistCompleted;
        
        public event System.EventHandler<InsertArtistCompletedEventArgs> InsertArtistCompleted;
        
        public event System.EventHandler<DeleteArtistCompletedEventArgs> DeleteArtistCompleted;
        
        public event System.EventHandler<UpdateWorkCompletedEventArgs> UpdateWorkCompleted;
        
        public event System.EventHandler<InsertWorkCompletedEventArgs> InsertWorkCompleted;
        
        public event System.EventHandler<DeleteWorkCompletedEventArgs> DeleteWorkCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginGetArtistNames(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetArtistNames(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> Gallery4Phone.ServiceReference1.IService1.EndGetArtistNames(System.IAsyncResult result) {
            return base.Channel.EndGetArtistNames(result);
        }
        
        private System.IAsyncResult OnBeginGetArtistNames(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginGetArtistNames(callback, asyncState);
        }
        
        private object[] OnEndGetArtistNames(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndGetArtistNames(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetArtistNamesCompleted(object state) {
            if ((this.GetArtistNamesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetArtistNamesCompleted(this, new GetArtistNamesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetArtistNamesAsync() {
            this.GetArtistNamesAsync(null);
        }
        
        public void GetArtistNamesAsync(object userState) {
            if ((this.onBeginGetArtistNamesDelegate == null)) {
                this.onBeginGetArtistNamesDelegate = new BeginOperationDelegate(this.OnBeginGetArtistNames);
            }
            if ((this.onEndGetArtistNamesDelegate == null)) {
                this.onEndGetArtistNamesDelegate = new EndOperationDelegate(this.OnEndGetArtistNames);
            }
            if ((this.onGetArtistNamesCompletedDelegate == null)) {
                this.onGetArtistNamesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetArtistNamesCompleted);
            }
            base.InvokeAsync(this.onBeginGetArtistNamesDelegate, null, this.onEndGetArtistNamesDelegate, this.onGetArtistNamesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginGetArtist(string prArtistName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetArtist(prArtistName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gallery4Phone.ServiceReference1.clsArtist Gallery4Phone.ServiceReference1.IService1.EndGetArtist(System.IAsyncResult result) {
            return base.Channel.EndGetArtist(result);
        }
        
        private System.IAsyncResult OnBeginGetArtist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string prArtistName = ((string)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginGetArtist(prArtistName, callback, asyncState);
        }
        
        private object[] OnEndGetArtist(System.IAsyncResult result) {
            Gallery4Phone.ServiceReference1.clsArtist retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndGetArtist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetArtistCompleted(object state) {
            if ((this.GetArtistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetArtistCompleted(this, new GetArtistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetArtistAsync(string prArtistName) {
            this.GetArtistAsync(prArtistName, null);
        }
        
        public void GetArtistAsync(string prArtistName, object userState) {
            if ((this.onBeginGetArtistDelegate == null)) {
                this.onBeginGetArtistDelegate = new BeginOperationDelegate(this.OnBeginGetArtist);
            }
            if ((this.onEndGetArtistDelegate == null)) {
                this.onEndGetArtistDelegate = new EndOperationDelegate(this.OnEndGetArtist);
            }
            if ((this.onGetArtistCompletedDelegate == null)) {
                this.onGetArtistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetArtistCompleted);
            }
            base.InvokeAsync(this.onBeginGetArtistDelegate, new object[] {
                        prArtistName}, this.onEndGetArtistDelegate, this.onGetArtistCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginUpdateArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateArtist(prArtist, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Gallery4Phone.ServiceReference1.IService1.EndUpdateArtist(System.IAsyncResult result) {
            return base.Channel.EndUpdateArtist(result);
        }
        
        private System.IAsyncResult OnBeginUpdateArtist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gallery4Phone.ServiceReference1.clsArtist prArtist = ((Gallery4Phone.ServiceReference1.clsArtist)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginUpdateArtist(prArtist, callback, asyncState);
        }
        
        private object[] OnEndUpdateArtist(System.IAsyncResult result) {
            int retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndUpdateArtist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateArtistCompleted(object state) {
            if ((this.UpdateArtistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateArtistCompleted(this, new UpdateArtistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateArtistAsync(Gallery4Phone.ServiceReference1.clsArtist prArtist) {
            this.UpdateArtistAsync(prArtist, null);
        }
        
        public void UpdateArtistAsync(Gallery4Phone.ServiceReference1.clsArtist prArtist, object userState) {
            if ((this.onBeginUpdateArtistDelegate == null)) {
                this.onBeginUpdateArtistDelegate = new BeginOperationDelegate(this.OnBeginUpdateArtist);
            }
            if ((this.onEndUpdateArtistDelegate == null)) {
                this.onEndUpdateArtistDelegate = new EndOperationDelegate(this.OnEndUpdateArtist);
            }
            if ((this.onUpdateArtistCompletedDelegate == null)) {
                this.onUpdateArtistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateArtistCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateArtistDelegate, new object[] {
                        prArtist}, this.onEndUpdateArtistDelegate, this.onUpdateArtistCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginInsertArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertArtist(prArtist, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Gallery4Phone.ServiceReference1.IService1.EndInsertArtist(System.IAsyncResult result) {
            return base.Channel.EndInsertArtist(result);
        }
        
        private System.IAsyncResult OnBeginInsertArtist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gallery4Phone.ServiceReference1.clsArtist prArtist = ((Gallery4Phone.ServiceReference1.clsArtist)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginInsertArtist(prArtist, callback, asyncState);
        }
        
        private object[] OnEndInsertArtist(System.IAsyncResult result) {
            int retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndInsertArtist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertArtistCompleted(object state) {
            if ((this.InsertArtistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertArtistCompleted(this, new InsertArtistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertArtistAsync(Gallery4Phone.ServiceReference1.clsArtist prArtist) {
            this.InsertArtistAsync(prArtist, null);
        }
        
        public void InsertArtistAsync(Gallery4Phone.ServiceReference1.clsArtist prArtist, object userState) {
            if ((this.onBeginInsertArtistDelegate == null)) {
                this.onBeginInsertArtistDelegate = new BeginOperationDelegate(this.OnBeginInsertArtist);
            }
            if ((this.onEndInsertArtistDelegate == null)) {
                this.onEndInsertArtistDelegate = new EndOperationDelegate(this.OnEndInsertArtist);
            }
            if ((this.onInsertArtistCompletedDelegate == null)) {
                this.onInsertArtistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertArtistCompleted);
            }
            base.InvokeAsync(this.onBeginInsertArtistDelegate, new object[] {
                        prArtist}, this.onEndInsertArtistDelegate, this.onInsertArtistCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginDeleteArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteArtist(prArtist, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Gallery4Phone.ServiceReference1.IService1.EndDeleteArtist(System.IAsyncResult result) {
            return base.Channel.EndDeleteArtist(result);
        }
        
        private System.IAsyncResult OnBeginDeleteArtist(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gallery4Phone.ServiceReference1.clsArtist prArtist = ((Gallery4Phone.ServiceReference1.clsArtist)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginDeleteArtist(prArtist, callback, asyncState);
        }
        
        private object[] OnEndDeleteArtist(System.IAsyncResult result) {
            int retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndDeleteArtist(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteArtistCompleted(object state) {
            if ((this.DeleteArtistCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteArtistCompleted(this, new DeleteArtistCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteArtistAsync(Gallery4Phone.ServiceReference1.clsArtist prArtist) {
            this.DeleteArtistAsync(prArtist, null);
        }
        
        public void DeleteArtistAsync(Gallery4Phone.ServiceReference1.clsArtist prArtist, object userState) {
            if ((this.onBeginDeleteArtistDelegate == null)) {
                this.onBeginDeleteArtistDelegate = new BeginOperationDelegate(this.OnBeginDeleteArtist);
            }
            if ((this.onEndDeleteArtistDelegate == null)) {
                this.onEndDeleteArtistDelegate = new EndOperationDelegate(this.OnEndDeleteArtist);
            }
            if ((this.onDeleteArtistCompletedDelegate == null)) {
                this.onDeleteArtistCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteArtistCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteArtistDelegate, new object[] {
                        prArtist}, this.onEndDeleteArtistDelegate, this.onDeleteArtistCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginUpdateWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateWork(prWork, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Gallery4Phone.ServiceReference1.IService1.EndUpdateWork(System.IAsyncResult result) {
            return base.Channel.EndUpdateWork(result);
        }
        
        private System.IAsyncResult OnBeginUpdateWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gallery4Phone.ServiceReference1.clsWork prWork = ((Gallery4Phone.ServiceReference1.clsWork)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginUpdateWork(prWork, callback, asyncState);
        }
        
        private object[] OnEndUpdateWork(System.IAsyncResult result) {
            int retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndUpdateWork(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateWorkCompleted(object state) {
            if ((this.UpdateWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateWorkCompleted(this, new UpdateWorkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateWorkAsync(Gallery4Phone.ServiceReference1.clsWork prWork) {
            this.UpdateWorkAsync(prWork, null);
        }
        
        public void UpdateWorkAsync(Gallery4Phone.ServiceReference1.clsWork prWork, object userState) {
            if ((this.onBeginUpdateWorkDelegate == null)) {
                this.onBeginUpdateWorkDelegate = new BeginOperationDelegate(this.OnBeginUpdateWork);
            }
            if ((this.onEndUpdateWorkDelegate == null)) {
                this.onEndUpdateWorkDelegate = new EndOperationDelegate(this.OnEndUpdateWork);
            }
            if ((this.onUpdateWorkCompletedDelegate == null)) {
                this.onUpdateWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateWorkCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateWorkDelegate, new object[] {
                        prWork}, this.onEndUpdateWorkDelegate, this.onUpdateWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginInsertWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertWork(prWork, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Gallery4Phone.ServiceReference1.IService1.EndInsertWork(System.IAsyncResult result) {
            return base.Channel.EndInsertWork(result);
        }
        
        private System.IAsyncResult OnBeginInsertWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gallery4Phone.ServiceReference1.clsWork prWork = ((Gallery4Phone.ServiceReference1.clsWork)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginInsertWork(prWork, callback, asyncState);
        }
        
        private object[] OnEndInsertWork(System.IAsyncResult result) {
            int retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndInsertWork(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertWorkCompleted(object state) {
            if ((this.InsertWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertWorkCompleted(this, new InsertWorkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertWorkAsync(Gallery4Phone.ServiceReference1.clsWork prWork) {
            this.InsertWorkAsync(prWork, null);
        }
        
        public void InsertWorkAsync(Gallery4Phone.ServiceReference1.clsWork prWork, object userState) {
            if ((this.onBeginInsertWorkDelegate == null)) {
                this.onBeginInsertWorkDelegate = new BeginOperationDelegate(this.OnBeginInsertWork);
            }
            if ((this.onEndInsertWorkDelegate == null)) {
                this.onEndInsertWorkDelegate = new EndOperationDelegate(this.OnEndInsertWork);
            }
            if ((this.onInsertWorkCompletedDelegate == null)) {
                this.onInsertWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertWorkCompleted);
            }
            base.InvokeAsync(this.onBeginInsertWorkDelegate, new object[] {
                        prWork}, this.onEndInsertWorkDelegate, this.onInsertWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Gallery4Phone.ServiceReference1.IService1.BeginDeleteWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteWork(prWork, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int Gallery4Phone.ServiceReference1.IService1.EndDeleteWork(System.IAsyncResult result) {
            return base.Channel.EndDeleteWork(result);
        }
        
        private System.IAsyncResult OnBeginDeleteWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Gallery4Phone.ServiceReference1.clsWork prWork = ((Gallery4Phone.ServiceReference1.clsWork)(inValues[0]));
            return ((Gallery4Phone.ServiceReference1.IService1)(this)).BeginDeleteWork(prWork, callback, asyncState);
        }
        
        private object[] OnEndDeleteWork(System.IAsyncResult result) {
            int retVal = ((Gallery4Phone.ServiceReference1.IService1)(this)).EndDeleteWork(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteWorkCompleted(object state) {
            if ((this.DeleteWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteWorkCompleted(this, new DeleteWorkCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteWorkAsync(Gallery4Phone.ServiceReference1.clsWork prWork) {
            this.DeleteWorkAsync(prWork, null);
        }
        
        public void DeleteWorkAsync(Gallery4Phone.ServiceReference1.clsWork prWork, object userState) {
            if ((this.onBeginDeleteWorkDelegate == null)) {
                this.onBeginDeleteWorkDelegate = new BeginOperationDelegate(this.OnBeginDeleteWork);
            }
            if ((this.onEndDeleteWorkDelegate == null)) {
                this.onEndDeleteWorkDelegate = new EndOperationDelegate(this.OnEndDeleteWork);
            }
            if ((this.onDeleteWorkCompletedDelegate == null)) {
                this.onDeleteWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteWorkDelegate, new object[] {
                        prWork}, this.onEndDeleteWorkDelegate, this.onDeleteWorkCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Gallery4Phone.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Gallery4Phone.ServiceReference1.IService1>, Gallery4Phone.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Gallery4Phone.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetArtistNames(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetArtistNames", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetArtistNames(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetArtistNames", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetArtist(string prArtistName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prArtistName;
                System.IAsyncResult _result = base.BeginInvoke("GetArtist", _args, callback, asyncState);
                return _result;
            }
            
            public Gallery4Phone.ServiceReference1.clsArtist EndGetArtist(System.IAsyncResult result) {
                object[] _args = new object[0];
                Gallery4Phone.ServiceReference1.clsArtist _result = ((Gallery4Phone.ServiceReference1.clsArtist)(base.EndInvoke("GetArtist", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prArtist;
                System.IAsyncResult _result = base.BeginInvoke("UpdateArtist", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUpdateArtist(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("UpdateArtist", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prArtist;
                System.IAsyncResult _result = base.BeginInvoke("InsertArtist", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertArtist(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertArtist", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteArtist(Gallery4Phone.ServiceReference1.clsArtist prArtist, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prArtist;
                System.IAsyncResult _result = base.BeginInvoke("DeleteArtist", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDeleteArtist(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DeleteArtist", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prWork;
                System.IAsyncResult _result = base.BeginInvoke("UpdateWork", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUpdateWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("UpdateWork", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prWork;
                System.IAsyncResult _result = base.BeginInvoke("InsertWork", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertWork", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteWork(Gallery4Phone.ServiceReference1.clsWork prWork, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = prWork;
                System.IAsyncResult _result = base.BeginInvoke("DeleteWork", _args, callback, asyncState);
                return _result;
            }
            
            public int EndDeleteWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("DeleteWork", _args, result)));
                return _result;
            }
        }
    }
}
